diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: "left_wheel_joint"
  right_wheel: "right_wheel_joint"
  wheel_separation: 0.2
  wheel_radius: 0.065
  command_topic: "/cmd_vel"
  odom_topic: "/odom"
  publish_rate: 50
  base_frame_id: "base_link"
  odom_frame_id: "odom"

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  ros__parameters:
    publish_rate: 50

right_wheel_velocity_controller:
  type: "effort_controllers/JointVelocityController"
  ros__parameters:
    joint: "right_wheel_joint"
    command_interface: "velocity"
    pid:
      p: 10.0
      i: 0.1
      d: 0.1
      i_max: 1.0
      i_min: -1.0

left_wheel_velocity_controller:
  type: "effort_controllers/JointVelocityController"
  ros__parameters:
    joint: "left_wheel_joint"
    command_interface: "velocity"
    pid:
      p: 10.0
      i: 0.1
      d: 0.1
      i_max: 1.0
      i_min: -1.0

